# Generated by Django 3.1 on 2020-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_external_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEventSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('frontend-cafe', 'Frontend Cafe')], max_length=255)),
                ('params', models.TextField(blank=True)),
            ],
        ),
    ]
