# Generated by Django 3.1 on 2020-11-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_communityeventsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityeventsource',
            name='source',
            field=models.CharField(choices=[('frontend-cafe', 'Frontend Cafe'), ('meetup', 'Meetup')], max_length=255),
        ),
    ]
