# Generated by Django 3.1 on 2020-11-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_set_default_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.communityeventsource'),
        ),
    ]
