on:
  push:
    branches:
      - master
name: Deploy to production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install node dependencies
        run: yarn --frozen-lockfile
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Collect static files
        run: python manage.py collectstatic
      - name: Deploy to Prod
        run: npm run deploy:prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
